# Generated by Django 4.0.1 on 2022-04-02 11:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0002_alter_contact_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='choose_sport',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cricket', 'Cricket'), ('Kabaddi', 'Kabbaddi'), ('Badmintion', 'Badmintion'), ('Chess', 'Chess'), ('Volleyball', 'volleyball')], max_length=120),
        ),
    ]
