# Generated by Django 4.0.1 on 2022-04-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0003_alter_contact_choose_sport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='choose_sport',
            new_name='sport',
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
