# Generated by Django 4.0.1 on 2022-04-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0004_rename_choose_sport_contact_sport_alter_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sport',
        ),
    ]
