# Generated by Django 4.0.1 on 2022-04-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0005_remove_contact_gender_remove_contact_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
