# Generated by Django 4.0.1 on 2022-04-07 06:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0006_remove_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('others', 'others')], default='test', max_length=120, verbose_name=[('Male', 'Male'), ('Female', 'Female'), ('others', 'others')]),
        ),
        migrations.AddField(
            model_name='contact',
            name='sport',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cricket', 'Cricket'), ('Kabaddi', 'Kabbaddi'), ('Badmintion', 'Badmintion'), ('Chess', 'Chess'), ('Volleyball', 'volleyball')], default='test', max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=120),
        ),
    ]
