# Generated by Django 4.0.1 on 2022-04-07 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0007_contact_gender_contact_sport_alter_contact_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='con',
        ),
    ]
