# Generated by Django 4.0.1 on 2022-04-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0009_contact_delete_con'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
